# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8064a0f9f77a7ec78b9561829ff363e7e6af9a3992e546a0a0994fbf15e3004c8df55ab139faaf56171c334583d350362879992acd0e513134923f545ca304b6

test:
  secret_key_base: 878afcda981fe5bc4f34b4ce3b19d8d60d5d057a2a64414b0a9fad874bd2d4d7f10587d5d56df309679ec2580f962bb702dd35d24935784ade8d5efaea5ca7ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
